name: Build and Publish AAB to Play Store

on:
  push:
    branches:
      - main

jobs:
  build_aab:
    runs-on: ubuntu-latest
    if: ${{ vars.ENABLE_ANDROID_BUILD == 'true' }}
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Instalar dependencias
        run: npm ci

      - name: Cache de Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v2
        with:
          licenses: |
            android-sdk-license
            android-googletv-license
            android-sdk-preview-license

      - name: Preparar Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_CONTENT }}" | base64 -d > android/app/release.keystore

      - name: Generar AAB
        env:
          ORG_GRADLE_PROJECT_signingKeystoreFile: release.keystore
          ORG_GRADLE_PROJECT_signingStorePassword: ${{ secrets.STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyAlias: ${{ secrets.KEY_ALIAS }}
          ORG_GRADLE_PROJECT_signingKeyPassword: ${{ secrets.KEY_PASSWORD }}
        run: |
          cd android
          chmod +x gradlew  # Dar permisos de ejecución al archivo
          ./gradlew bundleRelease --no-daemon --build-cache

      - name: Guardar AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/*.aab

      # - name: Subir AAB a Play Store
      #   uses: r0adkll/upload-google-play@v1
      #   with:
      #     serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
      #     packageName: "com.payerapp" # Reemplaza con tu ID de paquete
      #     releaseFiles: android/app/build/outputs/bundle/release/*.aab
      #     track: production
      #     inAppUpdatePriority: 3
